<?php

namespace App\Core\Helpers;

class BankInfo
{

    protected static $banks = [
        [
            "id" => 17,
            "name" => "Ngân hàng TMCP Công thương Việt Nam",
            "code" => "ICB",
            "bin" => "970415",
            "short_name" => "VietinBank",
            "logo" => "https://cdn.vietqr.io/img/ICB.png",
        ],
        [
            "id" => 43,
            "name" => "Ngân hàng TMCP Ngoại Thương Việt Nam",
            "code" => "VCB",
            "bin" => "970436",
            "short_name" => "Vietcombank",
            "logo" => "https://cdn.vietqr.io/img/VCB.png",
        ],
        [
            "id" => 4,
            "name" => "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
            "code" => "BIDV",
            "bin" => "970418",
            "short_name" => "BIDV",
            "logo" => "https://cdn.vietqr.io/img/BIDV.png",
        ],
        [
            "id" => 42,
            "name" => "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam",
            "code" => "VBA",
            "bin" => "970405",
            "short_name" => "Agribank",
            "logo" => "https://cdn.vietqr.io/img/VBA.png",
        ],
        [
            "id" => 26,
            "name" => "Ngân hàng TMCP Phương Đông",
            "code" => "OCB",
            "bin" => "970448",
            "short_name" => "OCB",
            "logo" => "https://cdn.vietqr.io/img/OCB.png",
        ],
        [
            "id" => 21,
            "name" => "Ngân hàng TMCP Quân đội",
            "code" => "MB",
            "bin" => "970422",
            "short_name" => "MBBank",
            "logo" => "https://cdn.vietqr.io/img/MB.png",
        ],
        [
            "id" => 38,
            "name" => "Ngân hàng TMCP Kỹ thương Việt Nam",
            "code" => "TCB",
            "bin" => "970407",
            "short_name" => "Techcombank",
            "logo" => "https://cdn.vietqr.io/img/TCB.png",
        ],
        [
            "id" => 2,
            "name" => "Ngân hàng TMCP Á Châu",
            "code" => "ACB",
            "bin" => "970416",
            "short_name" => "ACB",
            "logo" => "https://cdn.vietqr.io/img/ACB.png",
        ],
        [
            "id" => 47,
            "name" => "Ngân hàng TMCP Việt Nam Thịnh Vượng",
            "code" => "VPB",
            "bin" => "970432",
            "short_name" => "VPBank",
            "logo" => "https://cdn.vietqr.io/img/VPB.png",
        ],
        [
            "id" => 39,
            "name" => "Ngân hàng TMCP Tiên Phong",
            "code" => "TPB",
            "bin" => "970423",
            "short_name" => "TPBank",
            "logo" => "https://cdn.vietqr.io/img/TPB.png",
        ],
        [
            "id" => 36,
            "name" => "Ngân hàng TMCP Sài Gòn Thương Tín",
            "code" => "STB",
            "bin" => "970403",
            "short_name" => "Sacombank",
            "logo" => "https://cdn.vietqr.io/img/STB.png",
        ],
        [
            "id" => 12,
            "name" => "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh",
            "code" => "HDB",
            "bin" => "970437",
            "short_name" => "HDBank",
            "logo" => "https://cdn.vietqr.io/img/HDB.png",
        ],
        [
            "id" => 44,
            "name" => "Ngân hàng TMCP Bản Việt",
            "code" => "VCCB",
            "bin" => "970454",
            "short_name" => "VietCapitalBank",
            "logo" => "https://cdn.vietqr.io/img/VCCB.png",
        ],
        [
            "id" => 31,
            "name" => "Ngân hàng TMCP Sài Gòn",
            "code" => "SCB",
            "bin" => "970429",
            "short_name" => "SCB",
            "logo" => "https://cdn.vietqr.io/img/SCB.png",
        ],
        [
            "id" => 45,
            "name" => "Ngân hàng TMCP Quốc tế Việt Nam",
            "code" => "VIB",
            "bin" => "970441",
            "short_name" => "VIB",
            "logo" => "https://cdn.vietqr.io/img/VIB.png",
        ],
        [
            "id" => 35,
            "name" => "Ngân hàng TMCP Sài Gòn - Hà Nội",
            "code" => "SHB",
            "bin" => "970443",
            "short_name" => "SHB",
            "logo" => "https://cdn.vietqr.io/img/SHB.png",
        ],
        [
            "id" => 10,
            "name" => "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam",
            "code" => "EIB",
            "bin" => "970431",
            "short_name" => "Eximbank",
            "logo" => "https://cdn.vietqr.io/img/EIB.png",
        ],
        [
            "id" => 22,
            "name" => "Ngân hàng TMCP Hàng Hải Việt Nam",
            "code" => "MSB",
            "bin" => "970426",
            "short_name" => "MSB",
            "logo" => "https://cdn.vietqr.io/img/MSB.png",
        ],
        [
            "id" => 53,
            "name" => "TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank",
            "code" => "CAKE",
            "bin" => "546034",
            "short_name" => "CAKE",
            "logo" => "https://cdn.vietqr.io/img/CAKE.png",
        ],
        [
            "id" => 54,
            "name" => "TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank",
            "code" => "Ubank",
            "bin" => "546035",
            "short_name" => "Ubank",
            "logo" => "https://cdn.vietqr.io/img/UBANK.png",
        ],
        [
            "id" => 57,
            "name" => "Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội",
            "code" => "VTLMONEY",
            "bin" => "971005",
            "short_name" => "ViettelMoney",
            "logo" => "https://cdn.vietqr.io/img/VIETTELMONEY.png",
        ],
        [
            "id" => 58,
            "name" => "Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)",
            "code" => "TIMO",
            "bin" => "963388",
            "short_name" => "Timo",
            "logo" => "https://vietqr.net/portal-service/resources/icons/TIMO.png",
        ],
        [
            "id" => 56,
            "name" => "VNPT Money",
            "code" => "VNPTMONEY",
            "bin" => "971011",
            "short_name" => "VNPTMoney",
            "logo" => "https://cdn.vietqr.io/img/VNPTMONEY.png",
        ],
        [
            "id" => 34,
            "name" => "Ngân hàng TMCP Sài Gòn Công Thương",
            "code" => "SGICB",
            "bin" => "970400",
            "short_name" => "SaigonBank",
            "logo" => "https://cdn.vietqr.io/img/SGICB.png",
        ],
        [
            "id" => 3,
            "name" => "Ngân hàng TMCP Bắc Á",
            "code" => "BAB",
            "bin" => "970409",
            "short_name" => "BacABank",
            "logo" => "https://cdn.vietqr.io/img/BAB.png",
        ],
        [
            "id" => 65,
            "name" => "CTCP Dịch Vụ Di Động Trực Tuyến",
            "code" => "momo",
            "bin" => "971025",
            "short_name" => "MoMo",
            "logo" => "https://cdn.vietqr.io/img/momo.png",
        ],
        [
            "id" => 64,
            "name" => "Ngân hàng TMCP Đại Chúng Việt Nam Ngân hàng số",
            "code" => "PVDB",
            "bin" => "971133",
            "short_name" => "PVcomBank Pay",
            "logo" => "https://cdn.vietqr.io/img/PVCB.png",
        ],
        [
            "id" => 30,
            "name" => "Ngân hàng TMCP Đại Chúng Việt Nam",
            "code" => "PVCB",
            "bin" => "970412",
            "short_name" => "PVcomBank",
            "logo" => "https://cdn.vietqr.io/img/PVCB.png",
        ],
        [
            "id" => 27,
            "name" => "Ngân hàng TNHH MTV Việt Nam Hiện Đại",
            "code" => "MBV",
            "bin" => "970414",
            "short_name" => "MBV",
            "logo" => "https://cdn.vietqr.io/img/MBV.png",
        ],
        [
            "id" => 24,
            "name" => "Ngân hàng TMCP Quốc Dân",
            "code" => "NCB",
            "bin" => "970419",
            "short_name" => "NCB",
            "logo" => "https://cdn.vietqr.io/img/NCB.png",
        ],
        [
            "id" => 37,
            "name" => "Ngân hàng TNHH MTV Shinhan Việt Nam",
            "code" => "SHBVN",
            "bin" => "970424",
            "short_name" => "ShinhanBank",
            "logo" => "https://cdn.vietqr.io/img/SHBVN.png",
        ],
        [
            "id" => 1,
            "name" => "Ngân hàng TMCP An Bình",
            "code" => "ABB",
            "bin" => "970425",
            "short_name" => "ABBANK",
            "logo" => "https://cdn.vietqr.io/img/ABB.png",
        ],
        [
            "id" => 41,
            "name" => "Ngân hàng TMCP Việt Á",
            "code" => "VAB",
            "bin" => "970427",
            "short_name" => "VietABank",
            "logo" => "https://cdn.vietqr.io/img/VAB.png",
        ],
        [
            "id" => 23,
            "name" => "Ngân hàng TMCP Nam Á",
            "code" => "NAB",
            "bin" => "970428",
            "short_name" => "NamABank",
            "logo" => "https://cdn.vietqr.io/img/NAB.png",
        ],
        [
            "id" => 29,
            "name" => "Ngân hàng TMCP Thịnh vượng và Phát triển",
            "code" => "PGB",
            "bin" => "970430",
            "short_name" => "PGBank",
            "logo" => "https://cdn.vietqr.io/img/PGB.png",
        ],
        [
            "id" => 46,
            "name" => "Ngân hàng TMCP Việt Nam Thương Tín",
            "code" => "VIETBANK",
            "bin" => "970433",
            "short_name" => "VietBank",
            "logo" => "https://cdn.vietqr.io/img/VIETBANK.png",
        ],
        [
            "id" => 5,
            "name" => "Ngân hàng TMCP Bảo Việt",
            "code" => "BVB",
            "bin" => "970438",
            "short_name" => "BaoVietBank",
            "logo" => "https://cdn.vietqr.io/img/BVB.png",
        ],
        [
            "id" => 33,
            "name" => "Ngân hàng TMCP Đông Nam Á",
            "code" => "SEAB",
            "bin" => "970440",
            "short_name" => "SeABank",
            "logo" => "https://cdn.vietqr.io/img/SEAB.png",
        ],
        [
            "id" => 52,
            "name" => "Ngân hàng Hợp tác xã Việt Nam",
            "code" => "COOPBANK",
            "bin" => "970446",
            "short_name" => "COOPBANK",
            "logo" => "https://cdn.vietqr.io/img/COOPBANK.png",
        ],
        [
            "id" => 20,
            "name" => "Ngân hàng TMCP Lộc Phát Việt Nam",
            "code" => "LPB",
            "bin" => "970449",
            "short_name" => "LPBank",
            "logo" => "https://cdn.vietqr.io/img/LPB.png",
        ],
        [
            "id" => 19,
            "name" => "Ngân hàng TMCP Kiên Long",
            "code" => "KLB",
            "bin" => "970452",
            "short_name" => "KienLongBank",
            "logo" => "https://cdn.vietqr.io/img/KLB.png",
        ],
        [
            "id" => 55,
            "name" => "Ngân hàng Đại chúng TNHH Kasikornbank",
            "code" => "KBank",
            "bin" => "668888",
            "short_name" => "KBank",
            "logo" => "https://cdn.vietqr.io/img/KBANK.png",
        ],
        [
            "id" => 62,
            "name" => "Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam) ",
            "code" => "MAFC",
            "bin" => "977777",
            "short_name" => "MAFC",
            "logo" => "https://cdn.vietqr.io/img/MAFC.png",
        ],
        [
            "id" => 13,
            "name" => "Ngân hàng TNHH MTV Hong Leong Việt Nam",
            "code" => "HLBVN",
            "bin" => "970442",
            "short_name" => "HongLeong",
            "logo" => "https://cdn.vietqr.io/img/HLBVN.png",
        ],
        [
            "id" => 61,
            "name" => "Ngân hàng KEB Hana – Chi nhánh Hà Nội",
            "code" => "KEBHANAHN",
            "bin" => "970467",
            "short_name" => "KEBHANAHN",
            "logo" => "https://cdn.vietqr.io/img/KEBHANAHN.png",
        ],
        [
            "id" => 60,
            "name" => "Ngân hàng KEB Hana – Chi nhánh Thành phố Hồ Chí Minh",
            "code" => "KEBHANAHCM",
            "bin" => "970466",
            "short_name" => "KEBHanaHCM",
            "logo" => "https://cdn.vietqr.io/img/KEBHANAHCM.png",
        ],
        [
            "id" => 59,
            "name" => "Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội",
            "code" => "CITIBANK",
            "bin" => "533948",
            "short_name" => "Citibank",
            "logo" => "https://cdn.vietqr.io/img/CITIBANK.png",
        ],
        [
            "id" => 6,
            "name" => "Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam",
            "code" => "CBB",
            "bin" => "970444",
            "short_name" => "CBBank",
            "logo" => "https://cdn.vietqr.io/img/CBB.png",
        ],
        [
            "id" => 7,
            "name" => "Ngân hàng TNHH MTV CIMB Việt Nam",
            "code" => "CIMB",
            "bin" => "422589",
            "short_name" => "CIMB",
            "logo" => "https://cdn.vietqr.io/img/CIMB.png",
        ],
        [
            "id" => 8,
            "name" => "DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh",
            "code" => "DBS",
            "bin" => "796500",
            "short_name" => "DBSBank",
            "logo" => "https://cdn.vietqr.io/img/DBS.png",
        ],
        [
            "id" => 9,
            "name" => "Ngân hàng TNHH MTV Số Vikki",
            "code" => "Vikki",
            "bin" => "970406",
            "short_name" => "Vikki",
            "logo" => "https://cdn.vietqr.io/img/Vikki.png",
        ],
        [
            "id" => 63,
            "name" => "Ngân hàng Chính sách Xã hội",
            "code" => "VBSP",
            "bin" => "999888",
            "short_name" => "VBSP",
            "logo" => "https://cdn.vietqr.io/img/VBSP.png",
        ],
        [
            "id" => 11,
            "name" => "Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu",
            "code" => "GPB",
            "bin" => "970408",
            "short_name" => "GPBank",
            "logo" => "https://cdn.vietqr.io/img/GPB.png",
        ],
        [
            "id" => 51,
            "name" => "Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh",
            "code" => "KBHCM",
            "bin" => "970463",
            "short_name" => "KookminHCM",
            "logo" => "https://cdn.vietqr.io/img/KBHCM.png",
        ],
        [
            "id" => 50,
            "name" => "Ngân hàng Kookmin - Chi nhánh Hà Nội",
            "code" => "KBHN",
            "bin" => "970462",
            "short_name" => "KookminHN",
            "logo" => "https://cdn.vietqr.io/img/KBHN.png",
        ],
        [
            "id" => 49,
            "name" => "Ngân hàng TNHH MTV Woori Việt Nam",
            "code" => "WVN",
            "bin" => "970457",
            "short_name" => "Woori",
            "logo" => "https://cdn.vietqr.io/img/WVN.png",
        ],
        [
            "id" => 48,
            "name" => "Ngân hàng Liên doanh Việt - Nga",
            "code" => "VRB",
            "bin" => "970421",
            "short_name" => "VRB",
            "logo" => "https://cdn.vietqr.io/img/VRB.png",
        ],
        [
            "id" => 14,
            "name" => "Ngân hàng TNHH MTV HSBC (Việt Nam)",
            "code" => "HSBC",
            "bin" => "458761",
            "short_name" => "HSBC",
            "logo" => "https://cdn.vietqr.io/img/HSBC.png",
        ],
        [
            "id" => 15,
            "name" => "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội",
            "code" => "IBK - HN",
            "bin" => "970455",
            "short_name" => "IBKHN",
            "logo" => "https://cdn.vietqr.io/img/IBK.png",
        ],
        [
            "id" => 16,
            "name" => "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh",
            "code" => "IBK - HCM",
            "bin" => "970456",
            "short_name" => "IBKHCM",
            "logo" => "https://cdn.vietqr.io/img/IBK.png",
        ],
        [
            "id" => 18,
            "name" => "Ngân hàng TNHH Indovina",
            "code" => "IVB",
            "bin" => "970434",
            "short_name" => "IndovinaBank",
            "logo" => "https://cdn.vietqr.io/img/IVB.png",
        ],
        [
            "id" => 40,
            "name" => "Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh",
            "code" => "UOB",
            "bin" => "970458",
            "short_name" => "UnitedOverseas",
            "logo" => "https://cdn.vietqr.io/img/UOB.png",
        ],
        [
            "id" => 25,
            "name" => "Ngân hàng Nonghyup - Chi nhánh Hà Nội",
            "code" => "NHB HN",
            "bin" => "801011",
            "short_name" => "Nonghyup",
            "logo" => "https://cdn.vietqr.io/img/NHB.png",
        ],
        [
            "id" => 32,
            "name" => "Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam",
            "code" => "SCVN",
            "bin" => "970410",
            "short_name" => "StandardChartered",
            "logo" => "https://cdn.vietqr.io/img/SCVN.png",
        ],
        [
            "id" => 28,
            "name" => "Ngân hàng TNHH MTV Public Việt Nam",
            "code" => "PBVN",
            "bin" => "970439",
            "short_name" => "PublicBank",
            "logo" => "https://cdn.vietqr.io/img/PBVN.png",
        ]
    ];

    public static function getBankByBin($bin)
    {
        // Chuyển về string để so sánh cho chắc chắn
        $bin = (string)$bin;
        foreach (self::$banks as $bank) {
            if ($bank['bin'] === $bin) {
                return $bank;
            }
        }
        return null;
    }


    public static function options(): array
    {
        $options = [];

        foreach (self::$banks as $bank) {
            $options[$bank['bin']] = "{$bank['short_name']} - ({$bank['name']})";
        }
        return $options;
    }
}
